name: Deploy
on: [push, workflow_dispatch]

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    permissions:
      id-token: write # Needed for auth with Deno Deploy
      contents: read # Needed to clone the repository

    steps:
      - name: Clone repository
        uses: actions/checkout@v4

      # Not using npm? Change `npm ci` to `yarn install` or `pnpm i`
      - name: Install dependencies
        uses: denoland/setup-deno@v2
        run: deno install

      # Not using npm? Change `npm run build` to `yarn build` or `pnpm run build`
      - name: Build Astro
        uses: denoland/setup-deno@v2
        run: deno task build

      - name: Upload to Deno Deploy
        uses: denoland/deployctl@v1
        with:
          project: recursos-disseny-expandit
          # entrypoint: dist/server/entry.mjs
          entrypoint: jsr:@std/http/file-server
          root: dist/client
